name: ci
run-name: ${{github.actor}} check my code  # <---- preset value of github username 
on:
  push:
    branches-ignore:  # <---- ignore the "ga-ignore-" branch when push
      - " ga-ignore-"
  pull_request:
    branches-ignore:  # <---- ignore the "ga-ignore-" branch when pull-request
      - " ga-ignore-"
jobs:

  check_program_compilation:  # <---- check if the program compil or not
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container: epitechcontent/epitest-docker:latest  # <---- use epitech image
    steps:

      - name: Checkout GH repository
        uses: actions/checkout@master
        with:
          repository: ''

      - name: Compile repository  # <---- compile the repository with Makefile
        run: cmake -S . -B build

      - name: build project
        run: cmake --build build

      - name: Check file  # <---- check if the binary exit and can be executed
        run: |
          for file in ${{ vars.EXECUTABLES }};do
             if [ ! -x "$file" ]; then
              echo"File $file does not exist or is not executable"
              exit 1
            fi
          done

  push_to_mirror:  # <---- if the envent is "push", copy the repository to the repository epitech
    runs-on: ubuntu-latest
    # needs:  run_tests
    needs: check_program_compilation
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.MIRROR_URL }}  # <---- environment variable initialized in github, her value is the URL of the Epitech repository
          ssh_private_key:
            ${{ secrets.GIT_ACTION_KEY }}  # <---- secret variable set in github repository (settings) which contain SSH private key
